### ISSUE TITLE
Feature: export to a sarif file

### ISSUE THREAD

**Issue by hazcod** [zaproxy/action-full-scan#16]
Since GitHub now supports SARIF files which contain security issues (now primarily used for code scanning), would be cool to re-use this for ZAP.

ZAP should support exporting findings to SARIF.

**Comment by psiinon** [comment]
SARIF is for Static results, ans as such may not be suitable for Dynamic ones. Eg I cant see a URL field apart from one thats part of a CVE...

**Comment by hazcod** [comment]
Hmm, too bad. Thanks for checking tough. 👍

**Comment by jmservera** [comment]
Now that there's a proposal for [SARIF support](https://github.com/zaproxy/zap-extensions/pull/4078), can we reactivate this one?
