### ISSUE TITLE
Add input to control Github issue creation

### ISSUE THREAD

**Issue by gtzoganis** [zaproxy/action-full-scan#25]
The "Action Baseline" action exposes the `allow_issue_writing` input that allows controlling whether issues will be opened for alerts or not. This input is missing from this action and this will be a problem if someone does not want to use this feature, eg if they use another tool for issue tracking. The reason is that if Github issues are disabled, the whole action will fail. 

I have already opened PR #24 if you think this makes sense and want to add this feature.

Thanks!

**Comment by thc202** [comment]
It's not necessary to create an issue if the pull request is already open.
