### ISSUE TITLE
Bug: Docker container is run as root

### ISSUE THREAD

**Issue by dicksnel** [zaproxy/action-full-scan#29]
Hi,

The action starts the container as root:

https://github.com/zaproxy/action-full-scan/blob/7a8da6d1ba5e8c68adba95340c53507a21b1ed14/index.js#L43

This causes compatibility issues and is security-wise not the best practice.

Does this have a valid reason, or should it be removed?

**Comment by thc202** [comment]
Being discussed in zaproxy/action-baseline#33.
