### ISSUE TITLE
feature: Add hook input

### ISSUE THREAD

**Issue by amandahla** [zaproxy/action-full-scan#57]
I want to use a hook script like [here](https://github.com/zaproxy/zaproxy/issues/6626) to create custom HTTP headers.

Locally it's:

```
sudo docker run --rm -v ${PWD}:/zap/wrk -t owasp/zap2docker-stable zap-full-scan.py -t http://target/ --hook "hook.py" -z "-addoninstall jython"
```

hook.py points to a script file:
```
zap.script.load('Add Header Script', 'httpsender', 'python : jython', '/zap/wrk/add_header_request.py')
```

Similar parameter: "rules_file_name".

**Comment by thc202** [comment]
You can provide additional arguments to the script with [`cmd_options`](https://github.com/zaproxy/action-full-scan#cmd_options).

**Comment by amandahla** [comment]
Wow, sure. My bad! Thanks.
