### ISSUE TITLE
GitHub - You have exceeded a secondary rate limit.

### ISSUE THREAD

**Issue by amandahla** [zaproxy/action-full-scan#59]
While running a scan, the workflow failed with the message:

```
2023-01-18T15:29:57.2895700Z Scanning process completed, starting to analyze the results!
2023-01-18T15:29:57.3263850Z [@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
2023-01-18T15:29:57.7910108Z ##[error]You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```

Is there something to be done to prevent that?

**Comment by psiinon** [comment]
We should check that we follow these guidelines: https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits

**Comment by richard-scott** [comment]
I got a similar result today...

```
Scanning process completed, starting to analyze the results!
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits
```

**Comment by alecor191** [comment]
We also started to run into this issue. Unfortunately, re-running doesn't work as workaround, as we keep hitting this issue. Is there a recommended way to work around this limitation?

**Comment by psiinon** [comment]
You could try running separate scans at different times with different smaller sets of active scan rules?
that should reduce the number of requests made per hour..

**Comment by thc202** [comment]
I will take a look.

**Comment by tjcampanella** [comment]
This secondary rate limit causes our pipeline to fail multiple times per day. We'd greatly appreciate a review of that pull request mentioned if that would fix the issue. Thanks.

**Comment by amey-tieto** [comment]
When we are expecting to get this issue (secondary rate limit) resolved. Thanks.

**Comment by psiinon** [comment]
@amey-tieto I dont know, when are you expecting it to be resolved?
ZAP is a community project, and that means if you really want something done then you need to get stuck in 😁 
FYI https://github.com/zaproxy/actions-common/pull/198 looks promising but its got conflicts and so cannot be merged right now.
