### ISSUE TITLE
Running an OWASP Full Scan via Github Action ( zaproxy/action-full-scan@v0.4.0 ) results in an error

### ISSUE THREAD

**Issue by rubenmamo** [zaproxy/action-full-scan#60]
### Describe the bug

An error is being thrown when trying to run a full scan via Github Actions. The errors started happening today without any changes to the workflow.

### Steps to reproduce the behavior

1. Run an Owasp Zap Full scan using a Github Action zaproxy/action-full-scan@v0.4.0
2. Scan fails with an error

### Expected behavior

Scan completes correctly

### Software versions

zaproxy/action-full-scan@v0.4.0

### Errors from the zap.log file

[Zap Log.txt](https://github.com/zaproxy/zaproxy/files/10881939/Zap.Log.txt)

### Would you like to help fix this issue?

- [x] Yes

**Comment by rubenmamo** [comment]
The latest failing run I have was 38 minutes ago. From the log it seems to be something wrong whilst installing the spiderAjax add-on.

**Comment by psiinon** [comment]
@rubenmamo we have identified an issue and re-released the stable docker image.
We believe this will fix this problem - can you confirm its ok for you now?

**Comment by thc202** [comment]
This will be tracked in zaproxy/zaproxy#7765.

**Comment by rubenmamo** [comment]
@psiinon I can confirm that this is ok now. Thanks for your help.
