### ISSUE TITLE
Github Actions: Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by akarmyzov** [zaproxy/action-full-scan#61]
Github Actions complains that Node.js version 12 is deprecated or will be soon:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: zaproxy/action-full-scan@v0.4.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
```

Could Node.js version for ZAP scan Github Action be updated to 16?

**Comment by kingthorin** [comment]
It already is. GitHub is displaying that on all action runs.

https://github.com/zaproxy/action-full-scan/blob/9d8d415c14cc2d12d03850eb89c049d513b31e92/.github/workflows/check-dist.yml#L26-L29

**Comment by marcellmueller** [comment]
The last [release](https://github.com/zaproxy/action-full-scan/releases) was in May 2022 and this fix was merged in October 2022. Looks like this is still an issue with just this action as we have updated the rest of our actions and only have a warning for this one.

**Comment by marcellmueller** [comment]
@kingthorin oh nice, thanks for the heads up! I think we will wait for the next release but this is good to know incase.
