### ISSUE TITLE
feature: ZAP full scan maximum time

### ISSUE THREAD

**Issue by vyastj** [zaproxy/action-full-scan#76]
Hi team,

Would it be possible to set the maximum run time on the active scan which is followed by a spider with the `cmd` options?

**Comment by lgmorand** [comment]
+1. sometimes, my zap is stuck (don't know the reason) and I'll like to set a timeout

**Comment by thc202** [comment]
It is indeed possible to use `cmd` as there are options for that:
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ascan/#maximum-scan-duration-minutes-0-is-unlimited
https://www.zaproxy.org/docs/desktop/ui/dialogs/options/ascan/#maximum-rule-duration-minutes-0-is-unlimited

e.g. `-z "-config scanner.maxScanDurationInMins=60"`
https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/
