### ISSUE TITLE
upload-artifact@v3 is deprecated

### ISSUE THREAD

**Issue by jc00ke** [zaproxy/action-full-scan#91]
https://github.com/zaproxy/action-full-scan/blob/a9fbae9d7b2aae20ee32fe3b400d760e65c4e9a1/.github/workflows/check-dist.yml#L47

This was [deprecated on April 14, 2024](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) and will not be usable on November 30, 2024. I hope it's an easy upgrade and that the [breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) don't impact this work.

**Comment by lgmorand** [comment]
deadline is 30 nov. after that, the action will be broken

**Comment by thc202** [comment]
This is an internal workflow which does not affect users of the action. Also updating the library in the action itself will break other users.

**Comment by lgmorand** [comment]
Thanks for the quick answer

"This is an internal workflow which does not affect users of the action" it does as it displays warnings when we use this action and thus, pretty sure the artefact won't be uploaded after 30th Nov. these warning are detected in our corporate env and trigger alerts

```text
Deprecation notice: v1, v2, and v3 of the artifact actions
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "zap_scan".
Please update your workflow to use v4 of the artifact actions.
```


" Also updating the library in the action itself will break other users." why is that ? new version and new tag isn't it ? furthermore, as some point, common-scan may not work anymore if the API used is removed by GH.

**Comment by thc202** [comment]
`check-dist.yml` is an internal and unpublished workflow, updaying the action there will have no effect to end users.

Because the new version does not yet support GHES. https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new

**Comment by thc202** [comment]
There are users running the action in GHES.

**Comment by lgmorand** [comment]
Yeah this point is clear but not you refuse to fix it and use tagging.
 
- for GHA you could use v4 and you can tag your version accordingly
- for GHES, they stick with the actual code
tagging is meant for that. to be able to fix it without having a breaking change.

if v4 is not supported by November, then your action won't work anymore.

**Comment by lgmorand** [comment]
That's my colleagues and... you have great hope my friend :) 

once bitten, twice shy
